# Generated by Django 3.1.6 on 2021-02-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=80)),
                ('bio', models.CharField(max_length=300)),
                ('sports', models.CharField(max_length=150)),
            ],
        ),
    ]
