# Generated by Django 3.1.6 on 2021-02-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUps', '0002_auto_20210211_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
