# Generated by Django 3.1.6 on 2021-02-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUps', '0004_accounts_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
