# Generated by Django 3.1.6 on 2021-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUps', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_players',
            field=models.IntegerField(null=True),
        ),
    ]
