# Generated by Django 3.1.6 on 2021-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUps', '0009_gameplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='temp',
            field=models.BooleanField(null=True),
        ),
    ]
